sudo: false

language: php
php:
  - 5.5

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
